# Generated by Django 3.0.3 on 2020-04-14 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20200413_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banners',
            name='img_url',
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name='banners',
            name='priority',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
